In [15]:
import pandas as pd
df = pd.read_csv('airline_passenger_satisfaction.csv')
df.head()

,Gender,customer_type,age,type_of_travel,customer_class,flight_distance,inflight_wifi_service,departure_arrival_time_convenient,ease_of_online_booking,gate_location,...,inflight_entertainment,onboard_service,leg_room_service,baggage_handling,checkin_service,inflight_service,cleanliness,departure_delay_in_minutes,arrival_delay_in_minutes,satisfaction
0,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,1,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [16]:
from tabulate import tabulate

table = [['Name' , 'Data Type', 'Units', 'Description'],
        ['Gender', 'String', 'NA', 'The gender of the passesnger whose satisfaction was measured],
        ['customer_type', 'String', 'NA', 'Indicates whether the passenger is a loyal customer of the company or flies with other companies'],
        ['age', 'String', 'Years', 'The age of the passenger']
        ['type_of_travel', 'String', 'NA', 'Indicates if the passenger is travelling for business or personal reasons'],
        ['customer_class', 'String', 'NA', "The class of the passenger's ticket indicating which class cabin the travelled in"],
        ['flight_distance', ' Integer', 'Unkown Distance Unit', 'The distance of the journey']
        ['inflight_wifi_service', 'Integer', 'Rating out of 5', 'Rating of the inflight wifi service']
        ['departure_arrival_time_convenient', ' Integer' , 'Rating out of 5', 'Rating of the convenience of the flight departure and arrival time'],
        ['ease_of_online_booking', ' Integer' , 'Rating out of 5', 'Rating of the online booking service for the flight'],
         ['gate_location'], ' Integer' , 'Rating out of 5', 'Rating of the convenience of the location of the boarding/arrival gates inside the airport'],
         ['food_and_drink', ' Integer' , 'Rating out of 5', 'Rating of the food and beverages available on the flight'],
         ['online_boarding', ' Integer' , 'Rating out of 5', 'Rating of the online check-in process'],
         ['leg_room_service', ' Integer' , 'Rating out of 5', 'Rating of the leg room in the passengers seat']
         ['baggage_handling', ' Integer' , 'Rating out of 5', "Rating of the care and speed with which the passenger's baggage was handled"],
         ['checkin_service', ' Integer' , 'Rating out of 5', 'Rating of the in person check-in service'],
         ['inflight_service', ' Integer' , 'Rating out of 5', 'Rating of the service provided by the flight attendents']
         ['cleanliness', ' Integer' , 'Rating out of 5', 'Rating of the cleanliness of the aircraft'],
         ['departure_delay_in_minutes', 'Integer', 'Minutes', 'The time in minutes that the departure of the flight was delayed by'],
         ['arrival_delay_in_minutes', 'Float', 'Minutes', 'The time in minutes that the arrival of the flight was delayed by'],
         ['satisfaction', 'String', 'NA', "Rating of the passenger's satisfcation with the flight in general"]
         
         print(tabulate(table, headers='firstrow', tablefmt='simple'))

SyntaxError: EOL while scanning string literal (Temp/ipykernel_22328/587302740.py, line 4)